# Generated by Django 2.2.3 on 2019-07-30 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='cleanup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_records', to='api.CleanUp'),
        ),
        migrations.AddField(
            model_name='record',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_records', to='api.Flat'),
        ),
        migrations.AddField(
            model_name='record',
            name='flatmate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flatmate_records', to='api.Flatmate'),
        ),
        migrations.AddField(
            model_name='record',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_records', to='api.Room'),
        ),
        migrations.AddField(
            model_name='flatmate',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flatmates', to='api.Flat'),
        ),
        migrations.AddField(
            model_name='flatmate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleanup',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup', to='api.Room'),
        ),
    ]
