# Generated by Django 2.2.3 on 2019-07-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190730_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='parent_mode',
            field=models.BooleanField(default=True),
        ),
    ]
