# Generated by Django 2.2.3 on 2019-07-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_record_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Room'),
        ),
    ]
