# Generated by Django 2.2.3 on 2019-07-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_record_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='flat',
        ),
    ]
