# Generated by Django 2.2.3 on 2019-07-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_record_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='room_id',
            field=models.SmallIntegerField(null=True),
        ),
    ]
