# Generated by Django 2.2.3 on 2019-07-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_flat_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='room_id',
        ),
        migrations.AddField(
            model_name='record',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Flat'),
        ),
    ]
