# Generated by Django 2.2.3 on 2019-07-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190710_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatmate',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleanup', to='api.Room'),
        ),
        migrations.AlterField(
            model_name='flatmate',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flatmates', to='api.Flat'),
        ),
        migrations.AlterField(
            model_name='record',
            name='cleanup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_records', to='api.CleanUp'),
        ),
        migrations.AlterField(
            model_name='record',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flat_records', to='api.Flat'),
        ),
        migrations.AlterField(
            model_name='record',
            name='flatmate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flatmate_records', to='api.Flatmate'),
        ),
        migrations.AlterField(
            model_name='record',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_records', to='api.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.Flat'),
        ),
    ]
