# Generated by Django 2.2.3 on 2019-07-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190717_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
