# Generated by Django 2.2.3 on 2019-07-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190727_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='points',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
