# Generated by Django 2.2.3 on 2019-07-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_auto_20190730_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_parent',
            field=models.BooleanField(default=False, help_text='Designates whether this user should assign tasksIn ParentMode is const (api.models.parent_mode = True); in StudentMode changing periodically', verbose_name='is parent'),
        ),
    ]
